Repository mbj/mhs, pull requests merged in 2023-05, with the labels that each got.

#194 Add pre database objects definition parser changes
  pgt/package.yaml
  pgt/pgt.cabal
  pgt/src/PGT/Output/Golden.hs
  pgt/src/PGT/Output/Render.hs
  pgt/src/PGT/Output/Text.hs
  pgt/src/PGT/Prelude.hs
Labels: merge-ready

#193 Add database objects definition parser
  pgt/pgt.cabal
  pgt/src/PGT/Output/Definition.hs
  pgt/src/PGT/Output/Definition/examples/composite-type.expected
  pgt/src/PGT/Output/Definition/examples/composite-type.expected.parsed
  pgt/src/PGT/Output/Definition/examples/domain.expected
  pgt/src/PGT/Output/Definition/examples/domain.expected.parsed
  pgt/src/PGT/Output/Definition/examples/failure-on-invalid-function.expected
  pgt/src/PGT/Output/Definition/examples/failure-on-invalid-function.expected.parsed
  pgt/src/PGT/Output/Definition/examples/failure-on-invalid-view.expected
  pgt/src/PGT/Output/Definition/examples/failure-on-invalid-view.expected.parsed
  pgt/src/PGT/Output/Definition/examples/function.expected
  pgt/src/PGT/Output/Definition/examples/function.expected.parsed
  pgt/src/PGT/Output/Definition/examples/view.expected
  pgt/src/PGT/Output/Definition/examples/view.expected.parsed
  pgt/test/Test.hs
Labels: merge-ready

#195 Add PGT.Output.RowCount
  pgt/pgt.cabal
  pgt/src/PGT/Output/RowCount.hs
Labels: merge-ready

#196 Add PGT.Output.Test.Comments parser
  pgt/pgt.cabal
  pgt/src/PGT/Output/Test/Comments.hs
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-comments.expected
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-comments.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-error-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-error-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-row-count-1.expected
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-row-count-1.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-row-count-2.expected
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-row-count-2.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-row-count-3.expected
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-invalid-row-count-3.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-missing-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-missing-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-non-alpha-num-first-letter-comments.expected
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-non-alpha-num-first-letter-comments.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-partial-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/failure-on-partial-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/success-error-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/success-error-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/success-row-count-1.expected
  pgt/src/PGT/Output/Test/Comments/examples/success-row-count-1.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/success-row-count-2.expected
  pgt/src/PGT/Output/Test/Comments/examples/success-row-count-2.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/success-row-count-3.expected
  pgt/src/PGT/Output/Test/Comments/examples/success-row-count-3.expected.parsed
  pgt/test/Test.hs
Labels: merge-ready

#198 Add PGT.Output.Test.QueryPlan parser
  pgt/pgt.cabal
  pgt/src/PGT/Output/Test/QueryPlan.hs
  pgt/src/PGT/Output/Test/QueryPlan/examples/success-1.expected
  pgt/src/PGT/Output/Test/QueryPlan/examples/success-1.expected.parsed
  pgt/src/PGT/Output/Test/QueryPlan/examples/success-2.expected
  pgt/src/PGT/Output/Test/QueryPlan/examples/success-2.expected.parsed
  pgt/test/Test.hs
Labels: merge-ready

#197 Add PGT.Output.Test.Result parser
  pgt/pgt.cabal
  pgt/src/PGT/Output/Test/Result.hs
  pgt/src/PGT/Output/Test/Result/examples/error-result-1.expected
  pgt/src/PGT/Output/Test/Result/examples/error-result-1.expected.parsed
  pgt/src/PGT/Output/Test/Result/examples/error-result-2.expected
  pgt/src/PGT/Output/Test/Result/examples/error-result-2.expected.parsed
  pgt/src/PGT/Output/Test/Result/examples/error-result-3.expected
  pgt/src/PGT/Output/Test/Result/examples/error-result-3.expected.parsed
  pgt/src/PGT/Output/Test/Result/examples/error-result-4.expected
  pgt/src/PGT/Output/Test/Result/examples/error-result-4.expected.parsed
  pgt/src/PGT/Output/Test/Result/examples/json-records.expected
  pgt/src/PGT/Output/Test/Result/examples/json-records.expected.parsed
  pgt/src/PGT/Output/Test/Result/examples/json-rows.expected
  pgt/src/PGT/Output/Test/Result/examples/json-rows.expected.parsed
  pgt/src/PGT/Output/Test/Result/examples/rows.expected
  pgt/src/PGT/Output/Test/Result/examples/rows.expected.parsed
  pgt/src/PGT/Output/Test/Result/examples/zero-rows.expected
  pgt/src/PGT/Output/Test/Result/examples/zero-rows.expected.parsed
  pgt/test/Test.hs
Labels: merge-ready

#199 Add PGT.Output.Test parser
  pgt/pgt.cabal
  pgt/src/PGT/Output/Test.hs
  pgt/src/PGT/Output/Test/examples/failure-on-extra-line-after-comments.expected
  pgt/src/PGT/Output/Test/examples/failure-on-extra-line-after-comments.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-error-comment-1.expected
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-error-comment-1.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-error-comment-2.expected
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-error-comment-2.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-error-result.expected
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-error-result.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-records-count.expected
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-records-count.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-rows-count.expected
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-rows-count.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-zero-rows-count.expected
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-zero-rows-count.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-missing-line-after-comments.expected
  pgt/src/PGT/Output/Test/examples/failure-on-missing-line-after-comments.expected.parsed
  pgt/src/PGT/Output/Test/examples/success-with-query-plan.expected
  pgt/src/PGT/Output/Test/examples/success-with-query-plan.expected.parsed
  pgt/test/Test.hs
Labels: merge-ready

#200 Add PGT.Output.TestSuite parser
  pgt/pgt.cabal
  pgt/src/PGT/Output/TestSuite.hs
  pgt/src/PGT/Output/TestSuite/examples/failure-on-extra-line-after-definitions.expected
  pgt/src/PGT/Output/TestSuite/examples/failure-on-extra-line-after-definitions.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/failure-on-missing-test.expected
  pgt/src/PGT/Output/TestSuite/examples/failure-on-missing-test.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/failure-on-unexpected-text-after-defintion.expected
  pgt/src/PGT/Output/TestSuite/examples/failure-on-unexpected-text-after-defintion.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/success-with-multiple-definitions.expected
  pgt/src/PGT/Output/TestSuite/examples/success-with-multiple-definitions.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/success-with-multiple-tests.expected
  pgt/src/PGT/Output/TestSuite/examples/success-with-multiple-tests.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/success-with-out-defintions.expected
  pgt/src/PGT/Output/TestSuite/examples/success-with-out-defintions.expected.parsed
  pgt/test/Test.hs
Labels: merge-ready

#189 Add PGT CLI with linting & query-plan normalization
  pgt/pgt.cabal
  pgt/src/PGT.hs
  pgt/src/PGT/CLI.hs
  pgt/src/PGT/Output.hs
  pgt/src/PGT/Output/examples/success-with-multiple-test-suites.expected
  pgt/src/PGT/Output/examples/success-with-multiple-test-suites.expected.parsed
  pgt/src/PGT/Output/examples/success-with-single-test-suite.expected
  pgt/src/PGT/Output/examples/success-with-single-test-suite.expected.parsed
  pgt/test/Test.hs
Labels: merge-ready

#188 Add HTTP.MClient.{TransactionDecoder, send'}
  http-mclient/src/Network/HTTP/MClient.hs
Labels: merge-ready

#206 Change stack deploy cli
  stack-deploy/src/StackDeploy/CLI.hs
  stack-deploy/src/StackDeploy/CLI/Utils.hs
Labels: review-ready

#207 Fix source-constraints on GHC 9.4 to respect -Werror flag
  bounded/test/stack-9.2-dependencies.txt
  bounded/test/stack-9.4-dependencies.txt
  cbt/test/stack-9.2-dependencies.txt
  cbt/test/stack-9.4-dependencies.txt
  conversions/test/stack-9.2-dependencies.txt
  conversions/test/stack-9.4-dependencies.txt
  db-migrations/test/stack-9.2-dependencies.txt
  db-migrations/test/stack-9.4-dependencies.txt
  dbt-postgresql-connection/test/stack-9.2-dependencies.txt
  dbt-postgresql-connection/test/stack-9.4-dependencies.txt
  dbt-postgresql-container/test/stack-9.2-dependencies.txt
  dbt-postgresql-container/test/stack-9.4-dependencies.txt
  devtools/test/stack-9.2-dependencies.txt
  devtools/test/stack-9.4-dependencies.txt
  http-mclient/test/stack-9.2-dependencies.txt
  http-mclient/test/stack-9.4-dependencies.txt
  lambda-alb/test/stack-9.2-dependencies.txt
  lambda-alb/test/stack-9.4-dependencies.txt
  lambda-runtime/test/stack-9.2-dependencies.txt
  lambda-runtime/test/stack-9.4-dependencies.txt
  lht/test/stack-9.2-dependencies.txt
  lht/test/stack-9.4-dependencies.txt
  mio-amazonka/test/stack-9.2-dependencies.txt
  mio-amazonka/test/stack-9.4-dependencies.txt
  mio-core/test/stack-9.2-dependencies.txt
  mio-core/test/stack-9.4-dependencies.txt
  mio-log/test/stack-9.2-dependencies.txt
  mio-log/test/stack-9.4-dependencies.txt
  oauth/test/stack-9.2-dependencies.txt
  oauth/test/stack-9.4-dependencies.txt
  openapi/test/stack-9.2-dependencies.txt
  openapi/test/stack-9.4-dependencies.txt
  pgt/test/stack-9.2-dependencies.txt
  pgt/test/stack-9.4-dependencies.txt
  source-constraints/package.yaml
  source-constraints/source-constraints.cabal
  source-constraints/src/SourceConstraints.hs
  source-constraints/test/Spec.hs
  stack-deploy/test/stack-9.2-dependencies.txt
  stack-deploy/test/stack-9.4-dependencies.txt
  xray/test/stack-9.2-dependencies.txt
  xray/test/stack-9.4-dependencies.txt
Labels: review-ready

#210 Change to use RowCount.parse
  pgt/src/PGT/Output/RowCount.hs
  pgt/src/PGT/Output/Test.hs
  pgt/src/PGT/Output/Test/Comments.hs
  pgt/src/PGT/Output/Test/Result.hs
Labels: enhancement, merge-ready

#211 Change Test.Result.parseRows to parse empty rows
  pgt/src/PGT/Output/Test.hs
  pgt/src/PGT/Output/Test/Result.hs
  pgt/src/PGT/Output/Test/Result/examples/zero-table-rows.expected
  pgt/src/PGT/Output/Test/Result/examples/zero-table-rows.expected.parsed
Labels: merge-ready

#213 Add parsing single line comments
  pgt/src/PGT/Output/Test/Comments.hs
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-comments.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-comments.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-error-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-error-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-row-count-1.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-row-count-1.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-row-count-2.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-row-count-2.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-row-count-3.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-row-count-3.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-missing-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-missing-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-non-alpha-num-first-letter-comments.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-non-alpha-num-first-letter-comments.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-partial-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-partial-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-error-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-error-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-row-count-1.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-row-count-1.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-row-count-2.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-row-count-2.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-row-count-3.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-row-count-3.expected.parsed
Labels: merge-ready

#212 Change PGT.Output.Test to parse sub-tests
  pgt/src/PGT/Output/Test.hs
  pgt/src/PGT/Output/Test/Comments.hs
  pgt/src/PGT/Output/Test/Comments/examples/comment/failure-on-invalid-error-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comment/failure-on-invalid-error-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comment/success-error-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comment/success-error-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comment/success-row-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comment/success-row-comment.expected.parsed
  pgt/src/PGT/Output/Test/examples/success-with-sub-tests.expected
  pgt/src/PGT/Output/Test/examples/success-with-sub-tests.expected.parsed
Labels: merge-ready

#214 Change Comment parsers to parse either pattern meta-comments
  pgt/package.yaml
  pgt/pgt.cabal
  pgt/src/PGT/Output/Test.hs
  pgt/src/PGT/Output/Test/Comments.hs
  pgt/src/PGT/Output/Test/Comments/examples/comment/success-on-failure-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comment/success-on-failure-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comment/success-on-success-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comment/success-on-success-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-on-failure-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-on-failure-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-on-success-meta-comment.expected
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-on-success-meta-comment.expected.parsed
  pgt/test/stack-9.2-dependencies.txt
  pgt/test/stack-9.4-dependencies.txt
Labels: merge-ready

#215 Change Definition.parse to support parsing Enum & table definitions
  pgt/src/PGT/Output/Definition.hs
  pgt/src/PGT/Output/Definition/examples/failure-on-invalid-function.expected
  pgt/src/PGT/Output/Definition/examples/failure-on-invalid-title.expected
  pgt/src/PGT/Output/Definition/examples/failure-on-invalid-title.expected.parsed
  pgt/src/PGT/Output/Definition/examples/failure-on-missing-title.expected
  pgt/src/PGT/Output/Definition/examples/failure-on-missing-title.expected.parsed
  pgt/src/PGT/Output/Definition/examples/table.expected
  pgt/src/PGT/Output/Definition/examples/table.expected.parsed
  pgt/src/PGT/Output/Definition/examples/types.expected
  pgt/src/PGT/Output/Definition/examples/types.expected.parsed
Labels: merge-ready

#218 Change to report line positions in error messages
  pgt/src/PGT/Output/RowCount.hs
  pgt/src/PGT/Output/Test.hs
  pgt/src/PGT/Output/Test/Comments.hs
  pgt/src/PGT/Output/Test/Comments/examples/comment/failure-on-invalid-error-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-comments.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-error-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-row-count-1.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-row-count-2.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-invalid-row-count-3.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-missing-meta-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-non-alpha-num-first-letter-comments.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/failure-on-partial-comment.expected.parsed
  pgt/src/PGT/Output/Test/Comments/examples/comments/success-row-count-1.expected.parsed
  pgt/src/PGT/Output/Test/QueryPlan.hs
  pgt/src/PGT/Output/Test/examples/failure-on-extra-line-after-comments.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-error-comment-1.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-error-comment-2.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-error-result.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-records-count.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-rows-count.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-invalid-zero-rows-count.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-missing-line-after-comments.expected.parsed
  pgt/src/PGT/Output/TestSuite.hs
  pgt/src/PGT/Output/TestSuite/examples/failure-on-empty-content.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/failure-on-empty-line-before-tests-without-definitions.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/failure-on-extra-line-after-definitions.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/failure-on-extra-line-after-error-results.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/failure-on-missing-2-empty-lines-tests-separator.expected.parsed
  pgt/src/PGT/Output/TestSuite/examples/failure-on-unexpected-text-after-defintion.expected.parsed
  pgt/src/PGT/Output/Text.hs
Labels: merge-ready

#219 Change PG.Output.Test.Result.parseError to parse more error varieties
  pgt/src/PGT/Output/Test/Result.hs
  pgt/src/PGT/Output/Test/Result/examples/error-result-5.expected
  pgt/src/PGT/Output/Test/Result/examples/error-result-5.expected.parsed
  pgt/src/PGT/Output/Test/Result/examples/error-warning-result.expected
  pgt/src/PGT/Output/Test/Result/examples/error-warning-result.expected.parsed
Labels: merge-ready

#220 Fix Test.Result.parseRecords to parse empty json in small tables
  pgt/src/PGT/Output/Test/Result.hs
  pgt/src/PGT/Output/Test/Result/examples/empty-json-records.expected
  pgt/src/PGT/Output/Test/Result/examples/empty-json-records.expected.parsed
Labels: merge-ready

#223 Change PGT.Output.Test to parse and render ALTER execution logs
  pgt/src/PGT/Output/Test.hs
  pgt/src/PGT/Output/Test/examples/success-with-alter-logs.expected
  pgt/src/PGT/Output/Test/examples/success-with-alter-logs.expected.parsed
  pgt/src/PGT/Output/Test/examples/success-with-error-result.expected
  pgt/src/PGT/Output/Test/examples/success-with-error-result.expected.parsed
  pgt/src/PGT/Output/Test/examples/success-with-rows.expected
  pgt/src/PGT/Output/Test/examples/success-with-rows.expected.parsed
Labels: merge-ready

#222 Change PGT.Output.Test.Result to parse and render tuple only results
  pgt/src/PGT/Output/Test.hs
  pgt/src/PGT/Output/Test/Result.hs
  pgt/src/PGT/Output/Test/Result/examples/multi-tuple-rows.expected
  pgt/src/PGT/Output/Test/Result/examples/multi-tuple-rows.expected.parsed
  pgt/src/PGT/Output/Test/Result/examples/single-tuple-rows.expected
  pgt/src/PGT/Output/Test/Result/examples/single-tuple-rows.expected.parsed
  pgt/src/PGT/Output/Test/examples/failure-on-multi-tuple-rows-with-invalid-row-count.expected
  pgt/src/PGT/Output/Test/examples/failure-on-multi-tuple-rows-with-invalid-row-count.expected.parsed
  pgt/src/PGT/Output/Test/examples/success-with-multi-tuple-rows.expected
  pgt/src/PGT/Output/Test/examples/success-with-multi-tuple-rows.expected.parsed
  pgt/src/PGT/Output/Test/examples/success-with-tuple-rows.expected
  pgt/src/PGT/Output/Test/examples/success-with-tuple-rows.expected.parsed
Labels: merge-ready

#224 Change PGT.runTests to post-process tests output with linter
  pgt/src/PGT.hs
Labels: merge-ready

#225 Change PGT update CLI to run with linting
  pgt/src/PGT.hs
  pgt/src/PGT/CLI.hs
Labels: merge-ready
